name: formatter

on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache 
        with: 
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Set Poetry config 
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install Dependencies
        run: poetry install --only dev
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Code Quality
        run: |
          poetry run isort . --check --diff
          poetry run black --check .
          poetry run flake8 .
          poetry run pytest -x